config/routes.rb
Rails.application.routes.draw do
  resources :pickups
  resources :trips
  resources :places
  devise_for :users
  root :to => "users#index"
  get '/admin', to: 'users#admin_home'
  get '/driver', to: 'users#driver_home'
  get '/passenger', to: 'users#passenger_home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pickup.rb
class Pickup < ApplicationRecord
    belongs_to :passenger, class_name: "User", foreign_key: "passenger_id"
    belongs_to :source, class_name: "Place", foreign_key: "source_id"
    belongs_to :destination, class_name: "Place", foreign_key: "destination_id"
    validate :accepted_time
    validates_presence_of :passenger
    validates_presence_of :source
    validates_presence_of :destination

    def accepted_time
      errors.add(:dep_time, "depature time can not be in the past") unless self.dep_time > DateTime.now
    end

end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  before_action :set_pickup, only: [:show, :edit, :update, :destroy]

  # GET /pickups
  # GET /pickups.json
  def index
    @pickups = Pickup.where(passenger_id: current_user.id)
  end

  # GET /pickups/1
  # GET /pickups/1.json
  def show
  end

  # GET /pickups/new
  def new
    @pickup = Pickup.new
  end

  # GET /pickups/1/edit
  def edit
  end

  # POST /pickups
  # POST /pickups.json
  def create
    @pickup = Pickup.new(pickup_params)

    respond_to do |format|
      if @pickup.save
        format.html { redirect_to @pickup, notice: 'Pickup was successfully created.' }
        format.json { render :show, status: :created, location: @pickup }
      else
        format.html { render :new }
        format.json { render json: @pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pickups/1
  # PATCH/PUT /pickups/1.json
  def update
    respond_to do |format|
      if @pickup.update(pickup_params)
        format.html { redirect_to @pickup, notice: 'Pickup was successfully updated.' }
        format.json { render :show, status: :ok, location: @pickup }
      else
        format.html { render :edit }
        format.json { render json: @pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pickups/1
  # DELETE /pickups/1.json
  def destroy
    @pickup.destroy
    respond_to do |format|
      format.html { redirect_to pickups_url, notice: 'Pickup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pickup
      @pickup = Pickup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pickup_params
      params.require(:pickup).permit( :source_id, :destination_id, :dep_time ).merge(passenger_id: current_user.id)
    end
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/views/pickups/_form.html.erb
<%= form_with(model: pickup, local: true, :html => {:id => "new_pickup"}) do |f| %>
  <% if pickup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pickup.errors.count, "error") %> prohibited this pickup from being saved:</h2>

      <ul>
        <% pickup.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='form-group'>
      <label for="dep_time">time</label>

    <%= f.datetime_field :dep_time, label: false, placeholder: "Select the date and time", class: "form-control" %>
  </div>
  <div class='form-group'>
      <label for="destination_id">destination</label>

    <%= f.select(:destination_id, places_for_select, {}, { class: 'form-control' }) %>
  </div>
  <div class='form-group'>
    <label for="source_id">source</label>

    <%= f.select(:source_id, places_for_select, {}, { class: 'form-control' }) %>
  </div>

  <div class="actions" >
    <%= f.submit(class:"btn btn-success") %>
  </div>
<% end %>

app/views/pickups/_list.html.erb
<table>
  <thead>
    <tr>
      <th> Time </th>
      <th> Source </th>
      <th> Destination <th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pickups.each do |pickup| %>
      <tr>
        <th> <%=I18n.l(pickup.dep_time.to_datetime, format: :long)%> </th>
        <th> <%=pickup.destination&.name%> </th>
        <th> <%=pickup.source&.name%> <th>
        <td><%= link_to 'Show', pickup %></td>
        <td><%= link_to 'Edit', edit_pickup_path(pickup) %></td>
        <td><%= link_to 'Destroy', pickup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pickups/edit.html.erb
<%= render "users/passenger_nav" %>

<h1>Editing Pickup</h1>

<%= render 'form', pickup: @pickup %>

<%= link_to 'Show', @pickup %> |
<%= link_to 'Back', pickups_path %>

app/views/pickups/index.html.erb
<%= render "users/passenger_nav" %>
<p id="notice"><%= notice %></p>

<h1>Pickups</h1>

<%= render 'list', trips: @pickups %>


<br>

<%= link_to 'New Pickup', new_pickup_path %>

app/views/pickups/new.html.erb
<%= render "users/passenger_nav" %>

 <div class="container-fluid">
<h1>New Pickup</h1>

<%= render 'form', pickup: @pickup %>

<%= link_to 'Back', pickups_path %>
</div>

app/views/pickups/show.html.erb
<%= render "users/passenger_nav" %>

<p id="notice"><%= notice %></p>
<h1> Pickup detatils</h1>
time:<p id="dep_time"> <%=I18n.l(@pickup.dep_time.to_datetime, format: :long)%></p>
destination: <p id="destination"><%=@pickup.destination&.name%> </p>
source: <p id="source"><%=@pickup.source&.name%> <p>
<%= link_to 'Edit', edit_pickup_path(@pickup) %> |
<%= link_to 'Back', pickups_path %>