config/routes.rb
Rails.application.routes.draw do
  resources :pickups
  resources :trips
  resources :places
  devise_for :users
  root :to => "users#index"
  get '/admin', to: 'users#admin_home'
  get '/driver', to: 'users#driver_home'
  get '/passenger', to: 'users#passenger_home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :full_name, :phone, :role, presence: true
  validates :phone, uniqueness: true
  validates :encrypted_password, presence: true, on: :create
  enum role: { driver: 0, passenger: 1 , admin: 2}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
        if current_user
            if current_user.role == "driver" 
                redirect_to drive_path
            elsif current_user.role == "passenger"
                redirect_to passenger_path
            elsif current_user.role == "admin" 
                redirect_to admin_path
            end
        else
            redirect_to new_user_session_path
        end
    end

    def admin_home
        @place = Place.new
    end
    def driver_home
        @trip = Trip.new
        @trips = Trip.where(driver_id: current_user.id)

    end
    def passenger_home
        @pickup = Pickup.new
        @pickups = Pickup.where(passenger_id: current_user.id)

    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_nav.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-light'>
  <a class='navbar-brand' href='<%=admin_path%>'>Admin</a>
  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNav' aria-controls='navbarNav' aria-expanded='false' aria-label='Toggle navigation'>
    <span class='navbar-toggler-icon'></span>
  </button>
  <div class='collapse navbar-collapse' id='navbarNav'>
    <ul class='navbar-nav'>
      <li class='nav-item '>
        <a class='nav-link' href='<%=admin_path%>'>Home <span class='sr-only'>(current)</span></a>
      </li>
      <li class='nav-item '>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class:'nav-link') %>   
      </li>
    </ul>

  </div>
</nav>

app/views/users/_driver_nav.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-light'>
  <a class='navbar-brand' href='<%=driver_path%>'><%=current_user.full_name%></a>
  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNav' aria-controls='navbarNav' aria-expanded='false' aria-label='Toggle navigation'>
    <span class='navbar-toggler-icon'></span>
  </button>
  <div class='collapse navbar-collapse' id='navbarNav'>
    <ul class='navbar-nav'>
      <li class='nav-item '>
        <a class='nav-link' href='<%=driver_path%>'>Home <span class='sr-only'>(current)</span></a>
      </li>
       <li class='nav-item '>
        <%= link_to('Trips', trips_path, class:'nav-link') %>   
      </li>
      <li class='nav-item '>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class:'nav-link') %>   
      </li>
     
    </ul>

  </div>
</nav>

app/views/users/_passenger_nav.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-light'>
  <a class='navbar-brand' href='<%=passenger_path%>'><%=current_user.full_name%></a>
  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNav' aria-controls='navbarNav' aria-expanded='false' aria-label='Toggle navigation'>
    <span class='navbar-toggler-icon'></span>
  </button>
  <div class='collapse navbar-collapse' id='navbarNav'>
    <ul class='navbar-nav'>
      <li class='nav-item '>
        <a class='nav-link' href='<%=passenger_path%>'>Home <span class='sr-only'>(current)</span></a>
      </li>
      <li class='nav-item '>
        <%= link_to('Pickups', pickups_path, class:'nav-link') %>   
      </li>
      <li class='nav-item '>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class:'nav-link') %>   
      </li>
    </ul>

  </div>
</nav>

app/views/users/admin_home.html.erb
<%= render "users/admin_nav" %>
<h1>Admin Panel</h1>
<%= link_to 'Places', places_path, class: "btn btn-inverse" %>

app/views/users/driver_home.html.erb
<%= render "users/driver_nav" %>
<h1><%=current_user.full_name%></h1>
<h2> Add new Trip</h2>
<%= render "trips/form", trip: @trip %>
<%= render "trips/list", trips: @trips %>

 

app/views/users/passenger_home.html.erb
<%= render "users/passenger_nav" %>
<h1>My Home page</h1>

<%= render "pickups/form", pickup: @pickup %>
<%= render "pickups/list", pickups: @pickups %>