config/routes.rb
Rails.application.routes.draw do
  resources :pickups
  resources :trips
  resources :places
  devise_for :users
  root :to => "users#index"
  get '/admin', to: 'users#admin_home'
  get '/driver', to: 'users#driver_home'
  get '/passenger', to: 'users#passenger_home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
    validates :name, :pos_lat, :pos_long, presence: true
    validates :name, uniqueness: true

    validates_numericality_of :pos_lat,
                            greater_than_or_equal_to: -90,
                            less_than_or_equal_to: 90
    validates_numericality_of :pos_long,
                            greater_than_or_equal_to: -180,
                            less_than_or_equal_to: 180

    validates_uniqueness_of :pos_long, scope: [:pos_lat]

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create    
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
     
      params.require(:place).permit(:pos_long, :pos_lat, :name)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
    def places_for_select
        Place.all.collect { |m| [m.name, m.id] }
    end
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-6">
    <%= f.text_field :name, class: "form-control", placeholder: "name ..." %>
  </div>
  <br>
  <%= f.hidden_field :pos_lat, value:"30.045322", id: "place_latitude" %>
  <%= f.hidden_field :pos_long, value:"31.231384", id: "place_longitude" %>
  

  <div class="col-md-10">
    <div id="map" style="width:690px;height:340px;" ></div>
  </div>
  <br>
  <div class="col-md-12">
    <div class="actions">
      <%= f.submit class:"btn btn-success" %>
    </div>
  </div>

<% end %>




 <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUapcCrkW7bNodeC4BNnVXXdoCCbmrO64&callback=initMap">
    </script>

<script>
// Initialize and add the map
function initMap() {
  var lat = document.getElementById('place_latitude').value;
    var lng = document.getElementById('place_longitude').value;
    
    var myCoords = new google.maps.LatLng(lat, lng);
    var mapOptions = {
    center: myCoords,
    zoom: 14
    };
    var map = new google.maps.Map(document.getElementById('map'), mapOptions);
    var marker = new google.maps.Marker({
        position: myCoords,
        animation: google.maps.Animation.DROP,
        map: map,
        draggable: true
    }); 
    function refreshMarker(){
    var lat = document.getElementById('place_latitude').value;
    var lng = document.getElementById('place_longitude').value;
    var myCoords = new google.maps.LatLng(lat, lng);
    marker.setPosition(myCoords);
    map.setCenter(marker.getPosition());   
}  
// when input values change call refreshMarker
document.getElementById('place_latitude').onchange = refreshMarker;
document.getElementById('place_longitude').onchange = refreshMarker;

// when marker is dragged update input values
marker.addListener('drag', function() {
    latlng = marker.getPosition();
    newlat=(Math.round(latlng.lat()*1000000))/1000000;
    newlng=(Math.round(latlng.lng()*1000000))/1000000;
    document.getElementById('place_latitude').value = newlat;
    document.getElementById('place_longitude').value = newlng;
});
// When drag ends, center (pan) the map on the marker position
marker.addListener('dragend', function() {
    map.panTo(marker.getPosition());   
});
}




    </script>

app/views/places/edit.html.erb
<%= render "users/admin_nav" %>
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<%= render "users/admin_nav" %>


<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td> <%=place.name %></td> 
        <td><%= link_to 'Show ', place %></td>
        <td><%= link_to 'Edit ', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy ', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<%= render "users/admin_nav" %>

<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<%= render "users/admin_nav" %>

<h1> <%=@place.name %> </h1>



<div id="map" style="width:690px;height:340px;" ></div>
<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>


<script>

    let lat = <%=@place.pos_lat%> ; 
    let lng = <%=@place.pos_long%> ; 
    let map;
    function initMap() {
     var uluru = {lat: lat, lng: lng};
    // The map, centered at Uluru
    var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 14, center: uluru});
    // The marker, positioned at Uluru
    var marker = new google.maps.Marker({position: uluru, map: map});
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUapcCrkW7bNodeC4BNnVXXdoCCbmrO64&callback=initMap"async defer></script>